### ISSUE TITLE
Telegram bot

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-web3id#14]
**Task description**

The telegram bot has functionality to interact with the user, and the verifier to obtain information about user's social media profiles.

**Subtasks**
- [x] Implement basic Telegram bot functionality
- [x] Answer `/verify` commands with a link to the verification dApp
- [x] Check verification status of other users with the `/check` command

**Comment by abizjak** [comment]
Deployed now, so closing.
