### ISSUE TITLE
Discord bot

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-web3id#15]
**Task description**

A companion task to #14 that has similar functionality, but targets discord instead.

**Subtasks**
- [x] Implement basic Telegram bot functionality
- [x] Answer `/verify` commands with a link to the verification dApp
- [x] Check verification status of other users with the `/check` command

**Comment by abizjak** [comment]
Deployed now, so closing.
