### ISSUE TITLE
Verifier that serves the bots

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-web3id#17]
**Task description**

- This is a service that maintains a database of verified credentials which users have proved to it
- Serves a dApp where a user can prove ownership/reveal.
  - Onboarding flow at some point to streamline and explain what users need,
    such as getting the credentials. Step 2.
- Exposes an API that bots use to
  - query status of credentials/usernames/userids, and if their credential
    is revoked on the chain then the service would mark it so in the database.
- (Optional) allows users to delete their own credentials from it via a dApp, so they are forgotten

Subtasks
- [x] Create API for bots
- [x] dApp frontend UI
- [x] Web3 ID credential verification

**Comment by abizjak** [comment]
Deployed now, so closing.
