### ISSUE TITLE
Web3ID: Documentation for issuers and verifiers

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-web3id#7]
**Task description**

Apart from wallet users there will be two major entities in the Web3ID ecosystem, issuers and verifiers.

We have tools, SDKs to help be an issuer and verifier. We need onboarding guides for using all these tools.

- [ ] Onboarding guide for being a verifier/user of credentials. This should refer to our hosted instance of the verifier.
- [ ] Onboarding guide for being an issuer. Both using the service and via NodeJS and Rust SDKs.
- [ ] Improve documentation for running services, add docker-compose examples.

**Comment by abizjak** [comment]
Initial draft is published as a preview of the developer documentation.

The remaining tasks to be completed once we are code-complete and have all the tooling ready to publish.

**Comment by abizjak** [comment]
This is part of developer documentation.
